### ISSUE TITLE
numba is also a requirement

### ISSUE THREAD

**Issue by rhiever** [l1n0b1/TurboGP#1]
I tried running the basic regression example and I also had to install the `numba` package. It may be worth documenting that requirement in the documentation.

**Comment by l1n0b1** [comment]
True, my bad!
The thing is, `numba` is optional, can be disabled, but I forgot I left it activated. 
I will clarify that, and how to turn it on or off in the requirements section.
Thanks!

**Comment by l1n0b1** [comment]
Added numba to "Optional" required libraries, as well as commented its decorators so it is not required by default
